//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourneyTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class match_winner_type
    {
        public match_winner_type()
        {
            this.matches = new HashSet<match>();
        }
    
        public int match_winner_type_id { get; set; }
        public string match_winner_type_value { get; set; }
    
        public virtual ICollection<match> matches { get; set; }
    }
}
