//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourneyTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class match
    {
        public int match_id { get; set; }
        public int tournament_id { get; set; }
        public int participant_number_one { get; set; }
        public int participant_number_two { get; set; }
        public Nullable<int> score_one { get; set; }
        public Nullable<int> score_two { get; set; }
        public Nullable<int> match_winner_type_id { get; set; }
        public string message { get; set; }
    
        public virtual match_winner_type match_winner_type { get; set; }
        public virtual participant participant { get; set; }
        public virtual participant participant1 { get; set; }
        public virtual tournament tournament { get; set; }
    }
}
