//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourneyTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class participant
    {
        public participant()
        {
            this.matches = new HashSet<match>();
            this.matches1 = new HashSet<match>();
            this.tournament_participant_rel = new HashSet<tournament_participant_rel>();
        }
    
        public int participant_id { get; set; }
        public string participant_name { get; set; }
    
        public virtual ICollection<match> matches { get; set; }
        public virtual ICollection<match> matches1 { get; set; }
        public virtual ICollection<tournament_participant_rel> tournament_participant_rel { get; set; }
    }
}
