//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourneyTracker
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TourneyTrackerDBEntities : DbContext
    {
        public TourneyTrackerDBEntities()
            : base("name=TourneyTrackerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> accounts { get; set; }
        public virtual DbSet<match> matches { get; set; }
        public virtual DbSet<match_winner_type> match_winner_type { get; set; }
        public virtual DbSet<participant> participants { get; set; }
        public virtual DbSet<tournament> tournaments { get; set; }
        public virtual DbSet<tournament_participant_rel> tournament_participant_rel { get; set; }
        public virtual DbSet<tournament_type> tournament_type { get; set; }
    }
}
