//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourneyTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class tournament_type
    {
        public tournament_type()
        {
            this.tournaments = new HashSet<tournament>();
        }
    
        public int tournament_type_id { get; set; }
        public string tournament_type_name { get; set; }
    
        public virtual ICollection<tournament> tournaments { get; set; }
    }
}
